### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by lamnhan066**
Update firebase_messaging to the latest major version

### CODE REVIEW

**Comment by rithik-dev** [comment]
Hey, @vursin, thank you for the PR.

One thing, the date in the CHANGELOG is wrong, please update that.

Also, why did you change the files in the example/ios folder? Is that needed?

**Comment by lamnhan066** [comment]
@rithik-dev My bad, I'll update it. 

About the example/ios, those files are automatically created when I upgrade the dependencies, do I need to remove them?

And when I tested it on the ios platform, it ran into errors because of the below lines:
https://github.com/rithik-dev/firebase_notifications_handler/blob/c5830702e4ed6d4391a0c586ffca9eb2390dcf58/lib/src/service.dart#L166-L168

**Comment by rithik-dev** [comment]
Yes, revert the example/ios files

Also, there are latest versions for other dependencies as well, update them to the latest version also.

Also, what error did you get when you ran on ios platform? I don't have a MacBook, so I have not tested this on ios devices.

**Comment by lamnhan066** [comment]
> Also, what error did you get when you ran on ios platform?

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): iOS settings must be set when targeting iOS platform.
#0      FlutterLocalNotificationsPlugin.initialize
package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:134
#1      PushNotificationService._initializeLocalNotifications
package:firebase_notifications_handler/src/service.dart:170
#2      PushNotificationService._notificationHandler
package:firebase_notifications_handler/src/service.dart:254
#3      PushNotificationService._onMessage
package:firebase_notifications_handler/src/service.dart:149
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```


> Also, there are latest versions for other dependencies as well,

Other dependencies are automatically upgraded when you run the upgrade command. I create this PR just because the firebase_messaging was updated in its major version so it can't be automatically upgraded.

> I don't have a MacBook, so I have not tested this on ios devices.

I think the example/ios was created because I used Macbook to improve the plugin. So, do I still need to revert the example/ios files?

I also improve the plugin on my [dev branch](https://github.com/vursin/firebase_notifications_handler/tree/dev) to fix the above ios platform issue. You can give it a look if you have time, it's still on testing so I think I shouldn't create a PR.

**Comment by rithik-dev** [comment]
Hey @vursin, I would say that you try to fix the iOS issue, that would be really helpful, and create a PR when you think it works as expected...

I'll merge this request, and update the other dependencies, and release a new version by tonight

Thank you for the submission...

**Pull request merged**
